spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/longodb
    username: postgres
    password: Windows12!@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true